set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

get_filename_component(SDK_ROOT
    "${CMAKE_CURRENT_LIST_DIR}/../../.."
    ABSOLUTE
)

set(TOOLCHAIN_DIR
    "${SDK_ROOT}/buildroot/output/rockchip_rk3566/host"
)
set(CMAKE_C_COMPILER
    "${TOOLCHAIN_DIR}/bin/aarch64-linux-gcc"
)
set(CMAKE_CXX_COMPILER
    "${TOOLCHAIN_DIR}/bin/aarch64-linux-g++"
)
set(CMAKE_SYSROOT
    "${TOOLCHAIN_DIR}/aarch64-buildroot-linux-gnu/sysroot"
)
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
